name: Destroy Infra
on:
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2

permissions:
      contents: read    # This is required for actions/checkout

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: run kics Scan
        uses: checkmarx/kics-github-action@94469746ec2c43de89a42fb9d2a80070f5d25b16
        with:
          path: '.'
          type: pulumi
          output_path: kics/
      # Display the results in json format
      - name: display kics results
        run: |
          cat kics/results.json

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: ${{ secrets.AWS_IAC_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@c7fad9e2f0b79653172b36538b8b34b3c0291952
        with:
          command: destroy
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
